In [2]:
import pandas as pd
import numpy as np
import re

In [3]:
#Importing CSV
df = pd.read_csv('airbnb.csv', encoding = "utf-8", low_memory=False)

# Initial Data check

In [4]:
df.head(5)

,Unnamed: 0,id,listing_url,scrape_id,last_scraped,name,summary,space,description,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,1,4867396,https://www.airbnb.com/rooms/4867396,2.016070e+13,03/07/2016,Appartement 60m2 Rue Legendre 75017,Au 2ème étage d'un bel immeuble joli 2 pièces ...,NaN,Au 2ème étage d'un bel immeuble joli 2 pièces ...,NaN,...,10.0,f,NaN,Paris,f,flexible,f,f,1,0.07
1,2,7704653,https://www.airbnb.com/rooms/7704653,2.016070e+13,04/07/2016,Appart au pied de l'arc de triomphe,Nous proposons cette appartement situé en plei...,L'appartement est composé de : - une grande ch...,Nous proposons cette appartement situé en plei...,NaN,...,NaN,f,NaN,Paris,f,flexible,f,f,1,NaN
2,3,2725029,https://www.airbnb.com/rooms/2725029,2.016070e+13,04/07/2016,Nice appartment in Batignolles,"Located in the very charming Batignolles, this...",NaN,"Located in the very charming Batignolles, this...",NaN,...,NaN,f,NaN,Paris,f,flexible,f,f,1,0.11
3,4,9337509,https://www.airbnb.com/rooms/9337509,2.016070e+13,03/07/2016,Charming flat near Batignolles,Welcome to my apartment ! This a quiet and cos...,NaN,Welcome to my apartment ! This a quiet and cos...,NaN,...,8.0,f,NaN,Paris,f,flexible,f,f,1,0.15
4,5,12928158,https://www.airbnb.com/rooms/12928158,2.016070e+13,04/07/2016,Spacious bedroom near the centre of Paris,"Spacious, quiet and bright room, ideal to expl...",NaN,"Spacious, quiet and bright room, ideal to expl...",NaN,...,10.0,f,NaN,Paris,f,flexible,f,f,1,2.00

In [5]:
df.tail(10)

,Unnamed: 0,id,listing_url,scrape_id,last_scraped,name,summary,space,description,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
52715,52716,13259313,https://www.airbnb.com/rooms/13259313,2.016070e+13,04/07/2016,Le Kremlin ensoleillé,"Mon logement est proche du centre ville, de la...",NaN,"Mon logement est proche du centre ville, de la...",NaN,...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
52716,52717,13708217,https://www.airbnb.com/rooms/13708217,2.016070e+13,04/07/2016,Appart cosy et grande tranquilité à côté de Paris,"En face de la Seine, à côté du bois de Boulogn...",L'appartement occupe le 1er étage d'une maison...,"En face de la Seine, à côté du bois de Boulogn...",Il offre une ambiance de village avec son peti...,...,NaN,f,NaN,NaN,f,strict,f,f,1,NaN
52717,52718,13519917,https://www.airbnb.com/rooms/13519917,2.016070e+13,03/07/2016,Studio neuf à Gentilly,À 5 minutes de la gare de Gentilly .,NaN,À 5 minutes de la gare de Gentilly .,NaN,...,10.0,f,NaN,NaN,f,flexible,f,f,1,1.00
52718,52719,7347584,https://www.airbnb.com/rooms/7347584,2.016070e+13,03/07/2016,Beau 2 pièces aux portes de Paris,Charmant 2 pièces de 50m² situé au Kremlin Bic...,Bel appartement moderne dans un immeuble sécur...,Charmant 2 pièces de 50m² situé au Kremlin Bic...,"Il est proche de plusieurs commerces, restaura...",...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN
52719,52720,13394731,https://www.airbnb.com/rooms/13394731,2.016070e+13,03/07/2016,Bel appartement proche de Paris,Une aubaine ! Mon logement est proche de PARIS...,NaN,Une aubaine ! Mon logement est proche de PARIS...,NaN,...,8.0,f,NaN,NaN,t,moderate,f,f,1,1.00
52720,52721,7184490,https://www.airbnb.com/rooms/7184490,2.016070e+13,04/07/2016,"Spacieux, lumineux et neuf","Grand appartement, neuf et fonctionnel. très a...",NaN,"Grand appartement, neuf et fonctionnel. très a...",NaN,...,10.0,f,NaN,NaN,f,flexible,f,t,1,0.18
52721,52722,13742629,https://www.airbnb.com/rooms/13742629,2.016070e+13,04/07/2016,Cosy Flat with Balcony 10min from Champs Elysées,Our cosy apartment anables you to be at 10 min...,NaN,Our cosy apartment anables you to be at 10 min...,NaN,...,10.0,f,NaN,NaN,f,flexible,f,f,1,1.00
52722,52723,13346291,https://www.airbnb.com/rooms/13346291,2.016070e+13,04/07/2016,Double rooms in 90m2 flat + balcony close to P...,"We propose you two double rooms in a bright, s...",The spacious and quiet apartment overlooks a s...,"We propose you two double rooms in a bright, s...",Welcome to the east of Paris ! Montreuil is so...,...,NaN,f,NaN,NaN,f,strict,f,f,1,NaN
52723,52724,13067536,https://www.airbnb.com/rooms/13067536,2.016070e+13,04/07/2016,APPARTMENT A IL DE FRANCE ( NEER PARIS),저희 집은 지하철 3호선 gallieni 역 근처2분거리에있습니다. 저희 집은 넓은...,NaN,저희 집은 지하철 3호선 gallieni 역 근처2분거리에있습니다. 저희 집은 넓은...,Line number 3 : opera -> gallieni (20mn) Bus ...,...,NaN,f,NaN,NaN,t,flexible,f,f,2,NaN
52724,52725,815362,https://www.airbnb.com/rooms/815362,2.016070e+13,03/07/2016,F2 en bordure de Paris,Très lumineux,"Il s'agit d'un 35m2 à la porte de Paris, 2 piè...",Très lumineux Il s'agit d'un 35m2 à la porte d...,"Calme, silencieux",...,NaN,f,NaN,NaN,f,flexible,f,f,1,NaN

# Data Description

In [6]:
df.describe()

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,52725.000000,5.272500e+04,5.272500e+04,5.272500e+04,52679.000000,52679.000000,0.0,52725.000000,52725.000000,52725.000000,...,52725.000000,37271.000000,37150.000000,37159.000000,37146.000000,37182.000000,37165.000000,37166.000000,52725.000000,38217.000000
mean,26363.000000,7.069608e+06,2.016070e+13,2.248560e+07,5.829496,5.829496,NaN,48.863662,2.344145,3.050564,...,12.585984,91.012181,9.412409,9.109395,9.596888,9.651767,9.443159,9.180918,4.086733,1.336022
std,15220.540808,4.180018e+06,0.000000e+00,2.034516e+07,28.974836,28.974836,NaN,0.018684,0.034203,1.463974,...,25.214627,8.815037,0.866503,1.125027,0.761183,0.737976,0.822557,0.913647,14.225319,1.393752
min,1.000000,2.623000e+03,2.016070e+13,2.626000e+03,0.000000,0.000000,NaN,48.812015,2.220685,1.000000,...,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,13182.000000,3.470301e+06,2.016070e+13,6.158190e+06,1.000000,1.000000,NaN,48.849945,2.322812,2.000000,...,0.000000,87.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,1.000000,0.360000
50%,26363.000000,6.965852e+06,2.016070e+13,1.588541e+07,1.000000,1.000000,NaN,48.864589,2.347175,2.000000,...,3.000000,93.000000,10.000000,9.000000,10.000000,10.000000,10.000000,9.000000,1.000000,0.900000
75%,39544.000000,1.074006e+07,2.016070e+13,3.434872e+07,2.000000,2.000000,NaN,48.879221,2.369070,4.000000,...,13.000000,97.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,1.870000
max,52725.000000,1.381956e+07,2.016070e+13,8.139705e+07,1024.000000,1024.000000,NaN,48.905977,2.474573,16.000000,...,392.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,155.000000,14.290000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52725 entries, 0 to 52724
Data columns (total 95 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        52725 non-null  int64
 1   id                                52725 non-null  int64
 2   listing_url                       52725 non-null  object
 3   scrape_id                         52725 non-null  float64
 4   last_scraped                      52725 non-null  object
 5   name                              52724 non-null  object
 6   summary                           49974 non-null  object
 7   space                             38457 non-null  object
 8   description                       52717 non-null  object
 9   neighborhood_overview             32216 non-null  object
 10  notes                             17287 non-null  object
 11  transit                           34171 non-null  object
 12  access                            27901 non-null  object
 13  interaction                       25819 non-null  object
 14  house_rules                       29986 non-null  object
 15  thumbnail_url                     39260 non-null  object
 16  medium_url                        39260 non-null  object
 17  picture_url                       52725 non-null  object
 18  xl_picture_url                    39260 non-null  object
 19  host_id                           52725 non-null  int64
 20  host_url                          52725 non-null  object
 21  host_name                         52679 non-null  object
 22  host_since                        52679 non-null  object
 23  host_location                     52508 non-null  object
 24  host_about                        30778 non-null  object
 25  host_response_time                40162 non-null  object
 26  host_response_rate                40162 non-null  object
 27  host_acceptance_rate              37088 non-null  object
 28  host_is_superhost                 52679 non-null  object
 29  host_thumbnail_url                52679 non-null  object
 30  host_picture_url                  52679 non-null  object
 31  host_neighbourhood                46184 non-null  object
 32  host_listings_count               52679 non-null  float64
 33  host_total_listings_count         52679 non-null  float64
 34  host_verifications                52679 non-null  object
 35  host_has_profile_pic              52679 non-null  object
 36  host_identity_verified            52679 non-null  object
 37  street                            52725 non-null  object
 38  neighbourhood                     45268 non-null  object
 39  neighbourhood_cleansed            52725 non-null  object
 40  neighbourhood_group_cleansed      0 non-null      float64
 41  city                              52714 non-null  object
 42  state                             52653 non-null  object
 43  zipcode                           52221 non-null  object
 44  market                            49450 non-null  object
 45  smart_location                    52725 non-null  object
 46  country_code                      52725 non-null  object
 47  country                           52725 non-null  object
 48  latitude                          52725 non-null  float64
 49  longitude                         52725 non-null  float64
 50  is_location_exact                 52725 non-null  object
 51  property_type                     52722 non-null  object
 52  room_type                         52725 non-null  object
 53  accommodates                      52725 non-null  int64
 54  bathrooms                         52482 non-null  float64
 55  bedrooms                          52532 non-null  float64
 56  beds                              52645 non-null  float64
 57  bed_type                          52725 non-null  object
 58  amenities                         52725 non-null  object
 59  square_feet                       2507 non-null   float64
 60  price                             52725 non-null  object
 61  weekly_price                      22691 non-null  object
 62  monthly_price                     15194 non-null  object
 63  security_deposit                  32404 non-null  object
 64  cleaning_fee                      32603 non-null  object
 65  guests_included                   52725 non-null  int64
 66  extra_people                      52725 non-null  object
 67  minimum_nights                    52725 non-null  int64
 68  maximum_nights                    52725 non-null  int64
 69  calendar_updated                  52725 non-null  object
 70  has_availability                  0 non-null      float64
 71  availability_30                   52725 non-null  int64
 72  availability_60                   52725 non-null  int64
 73  availability_90                   52725 non-null  int64
 74  availability_365                  52725 non-null  int64
 75  calendar_last_scraped             52725 non-null  object
 76  number_of_reviews                 52725 non-null  int64
 77  first_review                      38217 non-null  object
 78  last_review                       38216 non-null  object
 79  review_scores_rating              37271 non-null  float64
 80  review_scores_accuracy            37150 non-null  float64
 81  review_scores_cleanliness         37159 non-null  float64
 82  review_scores_checkin             37146 non-null  float64
 83  review_scores_communication       37182 non-null  float64
 84  review_scores_location            37165 non-null  float64
 85  review_scores_value               37166 non-null  float64
 86  requires_license                  52725 non-null  object
 87  license                           1 non-null      object
 88  jurisdiction_names                51726 non-null  object
 89  instant_bookable                  52725 non-null  object
 90  cancellation_policy               52725 non-null  object
 91  require_guest_profile_picture     52725 non-null  object
 92  require_guest_phone_verification  52725 non-null  object
 93  calculated_host_listings_count    52725 non-null  int64
 94  reviews_per_month                 38217 non-null  float64
dtypes: float64(19), int64(13), object(63)
memory usage: 38.2+ MB

# Missing Values Analysis

In [8]:
df.isna().sum()[df.isna().sum().values > 0].sort_values()

name                                1
property_type                       3
description                         8
city                               11
host_has_profile_pic               46
host_verifications                 46
host_total_listings_count          46
host_listings_count                46
host_picture_url                   46
host_thumbnail_url                 46
host_is_superhost                  46
host_since                         46
host_name                          46
host_identity_verified             46
state                              72
beds                               80
bedrooms                          193
host_location                     217
bathrooms                         243
zipcode                           504
jurisdiction_names                999
summary                          2751
market                           3275
host_neighbourhood               6541
neighbourhood                    7457
host_response_time              12563
host_response_rate              12563
xl_picture_url                  13465
medium_url                      13465
thumbnail_url                   13465
space                           14268
reviews_per_month               14508
first_review                    14508
last_review                     14509
review_scores_rating            15454
review_scores_communication     15543
review_scores_value             15559
review_scores_location          15560
review_scores_cleanliness       15566
review_scores_accuracy          15575
review_scores_checkin           15579
host_acceptance_rate            15637
transit                         18554
cleaning_fee                    20122
security_deposit                20321
neighborhood_overview           20509
host_about                      21947
house_rules                     22739
access                          24824
interaction                     26906
weekly_price                    30034
notes                           35438
monthly_price                   37531
square_feet                     50218
license                         52724
neighbourhood_group_cleansed    52725
has_availability                52725
dtype: int64

# Removing Columns with more than 65% of missing values

In [9]:
percentage = 65
df_processed = df.drop(df.isna().sum()[df.isna().sum() > (len(df)*percentage)/100].index, axis = 1)

In [10]:
df_processed.isna().sum()[df_processed.isna().sum() > 0].sort_values()

name                               1
property_type                      3
description                        8
city                              11
host_identity_verified            46
host_has_profile_pic              46
host_total_listings_count         46
host_listings_count               46
host_picture_url                  46
host_thumbnail_url                46
host_is_superhost                 46
host_since                        46
host_verifications                46
host_name                         46
state                             72
beds                              80
bedrooms                         193
host_location                    217
bathrooms                        243
zipcode                          504
jurisdiction_names               999
summary                         2751
market                          3275
host_neighbourhood              6541
neighbourhood                   7457
host_response_time             12563
host_response_rate             12563
xl_picture_url                 13465
thumbnail_url                  13465
medium_url                     13465
space                          14268
reviews_per_month              14508
first_review                   14508
last_review                    14509
review_scores_rating           15454
review_scores_communication    15543
review_scores_value            15559
review_scores_location         15560
review_scores_cleanliness      15566
review_scores_accuracy         15575
review_scores_checkin          15579
host_acceptance_rate           15637
transit                        18554
cleaning_fee                   20122
security_deposit               20321
neighborhood_overview          20509
host_about                     21947
house_rules                    22739
access                         24824
interaction                    26906
weekly_price                   30034
dtype: int64

# Removing columns

#### Checking unique values of columns

In [11]:
unique_values_sum = [(len(value), item) for item, value in df_processed.apply(lambda x : pd.unique(x), axis = 0).items()]
unique_values_sum.sort(key=lambda x: x[0])

unique_values_sum

[(1, 'scrape_id'),
 (1, 'requires_license'),
 (2, 'last_scraped'),
 (2, 'country_code'),
 (2, 'country'),
 (2, 'is_location_exact'),
 (2, 'calendar_last_scraped'),
 (2, 'jurisdiction_names'),
 (2, 'instant_bookable'),
 (2, 'require_guest_profile_picture'),
 (2, 'require_guest_phone_verification'),
 (3, 'host_is_superhost'),
 (3, 'host_has_profile_pic'),
 (3, 'host_identity_verified'),
 (3, 'room_type'),
 (5, 'host_response_time'),
 (5, 'bed_type'),
 (5, 'cancellation_policy'),
 (10, 'review_scores_accuracy'),
 (10, 'review_scores_cleanliness'),
 (10, 'review_scores_checkin'),
 (10, 'review_scores_communication'),
 (10, 'review_scores_location'),
 (10, 'review_scores_value'),
 (11, 'bedrooms'),
 (15, 'guests_included'),
 (16, 'accommodates'),
 (17, 'beds'),
 (18, 'bathrooms'),
 (20, 'neighbourhood_cleansed'),
 (20, 'property_type'),
 (30, 'market'),
 (31, 'availability_30'),
 (52, 'minimum_nights'),
 (53, 'state'),
 (53, 'calculated_host_listings_count'),
 (60, 'review_scores_rating'),
 (61, 'calendar_updated'),
 (61, 'availability_60'),
 (64, 'neighbourhood'),
 (74, 'host_listings_count'),
 (74, 'host_total_listings_count'),
 (79, 'zipcode'),
 (86, 'host_response_rate'),
 (89, 'extra_people'),
 (91, 'availability_90'),
 (95, 'host_acceptance_rate'),
 (136, 'host_verifications'),
 (136, 'city'),
 (137, 'smart_location'),
 (157, 'cleaning_fee'),
 (229, 'maximum_nights'),
 (231, 'host_neighbourhood'),
 (265, 'number_of_reviews'),
 (304, 'security_deposit'),
 (366, 'availability_365'),
 (498, 'price'),
 (828, 'reviews_per_month'),
 (1046, 'last_review'),
 (1186, 'weekly_price'),
 (1560, 'host_location'),
 (1946, 'first_review'),
 (2306, 'host_since'),
 (8531, 'street'),
 (9344, 'host_name'),
 (23618, 'interaction'),
 (23864, 'host_about'),
 (24472, 'access'),
 (26790, 'house_rules'),
 (31236, 'neighborhood_overview'),
 (33287, 'transit'),
 (37737, 'amenities'),
 (38142, 'space'),
 (39257, 'thumbnail_url'),
 (39257, 'medium_url'),
 (39257, 'xl_picture_url'),
 (44652, 'host_thumbnail_url'),
 (44652, 'host_picture_url'),
 (44874, 'host_id'),
 (44874, 'host_url'),
 (49378, 'summary'),
 (50132, 'name'),
 (52444, 'description'),
 (52503, 'latitude'),
 (52715, 'longitude'),
 (52719, 'picture_url'),
 (52725, 'Unnamed: 0'),
 (52725, 'id'),
 (52725, 'listing_url')]

#### Removing columns with same value for all the rows

In [12]:
columns_same_value = [elem[1] for elem in unique_values_sum if elem[0]==1]
columns_same_value

['scrape_id', 'requires_license']

In [13]:
df_processed = df_processed.drop(columns_same_value, axis = 1)

#### Removing reduntant information

In [14]:
#Identifying reduntant columns

print("Equal values: " + str((df.host_listings_count == df.host_total_listings_count).sum()))
print("Diferent values: ") #The different values are actuawlly the missing values
df.loc[(df.host_listings_count != df.host_total_listings_count),["host_listings_count","host_total_listings_count"]]

Equal values: 52679
Diferent values:

       host_listings_count  host_total_listings_count
121                    NaN                        NaN
431                    NaN                        NaN
4471                   NaN                        NaN
4971                   NaN                        NaN
5641                   NaN                        NaN
6780                   NaN                        NaN
8090                   NaN                        NaN
8101                   NaN                        NaN
9200                   NaN                        NaN
10293                  NaN                        NaN
10640                  NaN                        NaN
11536                  NaN                        NaN
12233                  NaN                        NaN
12234                  NaN                        NaN
12356                  NaN                        NaN
13884                  NaN                        NaN
15510                  NaN                        NaN
16000                  NaN                        NaN
16113                  NaN                        NaN
17684                  NaN                        NaN
22179                  NaN                        NaN
22180                  NaN                        NaN
23770                  NaN                        NaN
26605                  NaN                        NaN
27623                  NaN                        NaN
28336                  NaN                        NaN
28611                  NaN                        NaN
29623                  NaN                        NaN
29733                  NaN                        NaN
33193                  NaN                        NaN
35186                  NaN                        NaN
36441                  NaN                        NaN
38380                  NaN                        NaN
38435                  NaN                        NaN
40656                  NaN                        NaN
40661                  NaN                        NaN
43710                  NaN                        NaN
44513                  NaN                        NaN
44743                  NaN                        NaN
44927                  NaN                        NaN
45026                  NaN                        NaN
45202                  NaN                        NaN
47924                  NaN                        NaN
49480                  NaN                        NaN
50587                  NaN                        NaN
50720                  NaN                        NaN

In [15]:
#Dropping reduntant columns

df_processed = df_processed.drop("host_total_listings_count", axis = 1)

In [16]:
unique_values_sum = [(len(value), item) for item, value in df_processed.apply(lambda x : pd.unique(x), axis = 0).items()]
unique_values_sum.sort(key=lambda x: x[0])

unique_values_sum

[(2, 'last_scraped'),
 (2, 'country_code'),
 (2, 'country'),
 (2, 'is_location_exact'),
 (2, 'calendar_last_scraped'),
 (2, 'jurisdiction_names'),
 (2, 'instant_bookable'),
 (2, 'require_guest_profile_picture'),
 (2, 'require_guest_phone_verification'),
 (3, 'host_is_superhost'),
 (3, 'host_has_profile_pic'),
 (3, 'host_identity_verified'),
 (3, 'room_type'),
 (5, 'host_response_time'),
 (5, 'bed_type'),
 (5, 'cancellation_policy'),
 (10, 'review_scores_accuracy'),
 (10, 'review_scores_cleanliness'),
 (10, 'review_scores_checkin'),
 (10, 'review_scores_communication'),
 (10, 'review_scores_location'),
 (10, 'review_scores_value'),
 (11, 'bedrooms'),
 (15, 'guests_included'),
 (16, 'accommodates'),
 (17, 'beds'),
 (18, 'bathrooms'),
 (20, 'neighbourhood_cleansed'),
 (20, 'property_type'),
 (30, 'market'),
 (31, 'availability_30'),
 (52, 'minimum_nights'),
 (53, 'state'),
 (53, 'calculated_host_listings_count'),
 (60, 'review_scores_rating'),
 (61, 'calendar_updated'),
 (61, 'availability_60'),
 (64, 'neighbourhood'),
 (74, 'host_listings_count'),
 (79, 'zipcode'),
 (86, 'host_response_rate'),
 (89, 'extra_people'),
 (91, 'availability_90'),
 (95, 'host_acceptance_rate'),
 (136, 'host_verifications'),
 (136, 'city'),
 (137, 'smart_location'),
 (157, 'cleaning_fee'),
 (229, 'maximum_nights'),
 (231, 'host_neighbourhood'),
 (265, 'number_of_reviews'),
 (304, 'security_deposit'),
 (366, 'availability_365'),
 (498, 'price'),
 (828, 'reviews_per_month'),
 (1046, 'last_review'),
 (1186, 'weekly_price'),
 (1560, 'host_location'),
 (1946, 'first_review'),
 (2306, 'host_since'),
 (8531, 'street'),
 (9344, 'host_name'),
 (23618, 'interaction'),
 (23864, 'host_about'),
 (24472, 'access'),
 (26790, 'house_rules'),
 (31236, 'neighborhood_overview'),
 (33287, 'transit'),
 (37737, 'amenities'),
 (38142, 'space'),
 (39257, 'thumbnail_url'),
 (39257, 'medium_url'),
 (39257, 'xl_picture_url'),
 (44652, 'host_thumbnail_url'),
 (44652, 'host_picture_url'),
 (44874, 'host_id'),
 (44874, 'host_url'),
 (49378, 'summary'),
 (50132, 'name'),
 (52444, 'description'),
 (52503, 'latitude'),
 (52715, 'longitude'),
 (52719, 'picture_url'),
 (52725, 'Unnamed: 0'),
 (52725, 'id'),
 (52725, 'listing_url')]

#### Removing URLs

In [17]:
#Look for columns that end with url
pattern_url = re.compile(".+_url")
url_features = [col for col in df.columns if re.search(pattern_url, col)]

#Drop columns that contain url
df_processed = df_processed.drop(url_features, axis = 1)

In [18]:
df_processed.head(5)

,Unnamed: 0,id,last_scraped,name,summary,space,description,neighborhood_overview,transit,access,...,review_scores_communication,review_scores_location,review_scores_value,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,1,4867396,03/07/2016,Appartement 60m2 Rue Legendre 75017,Au 2ème étage d'un bel immeuble joli 2 pièces ...,NaN,Au 2ème étage d'un bel immeuble joli 2 pièces ...,NaN,NaN,NaN,...,10.0,10.0,10.0,Paris,f,flexible,f,f,1,0.07
1,2,7704653,04/07/2016,Appart au pied de l'arc de triomphe,Nous proposons cette appartement situé en plei...,L'appartement est composé de : - une grande ch...,Nous proposons cette appartement situé en plei...,NaN,NaN,NaN,...,NaN,NaN,NaN,Paris,f,flexible,f,f,1,NaN
2,3,2725029,04/07/2016,Nice appartment in Batignolles,"Located in the very charming Batignolles, this...",NaN,"Located in the very charming Batignolles, this...",NaN,NaN,NaN,...,NaN,NaN,NaN,Paris,f,flexible,f,f,1,0.11
3,4,9337509,03/07/2016,Charming flat near Batignolles,Welcome to my apartment ! This a quiet and cos...,NaN,Welcome to my apartment ! This a quiet and cos...,NaN,NaN,NaN,...,10.0,6.0,8.0,Paris,f,flexible,f,f,1,0.15
4,5,12928158,04/07/2016,Spacious bedroom near the centre of Paris,"Spacious, quiet and bright room, ideal to expl...",NaN,"Spacious, quiet and bright room, ideal to expl...",NaN,NaN,NaN,...,10.0,10.0,10.0,Paris,f,flexible,f,f,1,2.00

#### Removing unique identifiers

In [19]:
#Dropping unique identifiers (not usefull for the model)

pattern_id = re.compile(".*id.*")

unique_identifiers = [col for col in df_processed.columns if re.search(pattern_id, col)]
unique_identifiers

['id', 'host_id', 'host_identity_verified']

In [20]:
#Check results

#host_identity_verified CANNOT be removed at this point because it is not an unique ID
df_processed.host_identity_verified

0        f
1        f
2        f
3        t
4        t
        ..
52720    t
52721    t
52722    f
52723    f
52724    f
Name: host_identity_verified, Length: 52725, dtype: object

In [21]:
#id is unique id indeed
len(df.id.unique()) == len(df)

True

In [22]:
#host_id is not unique because same host can have different properties
len(df.host_id.unique()) == len(df)

False

In [23]:
#Remove unique id

df_processed = df_processed.drop("id", axis = 1)